"""making title unique

Revision ID: 9c3a3b0ff466
Revises: 816ff3844883
Create Date: 2025-08-21 14:11:47.201598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3a3b0ff466'
down_revision: Union[str, Sequence[str], None] = '816ff3844883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.create_unique_constraint("uq_tasks_title", ["title"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    # ### end Alembic commands ###
